// Colle ici les valeurs de ton projet Supabase (Settings > API).
window.AUTOLEAD_SUPABASE_URL = "sb_publishable_uJBQEjTN0LKw4-nyW3_Nag_sVlLIvFF";
window.AUTOLEAD_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzZGZ5Y3ppdWlxYmNmbmt2d3NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkxNTI3MDIsImV4cCI6MjEwNDcyODcwMn0.Ccgp6M2UHNieCHaPQqZhPTiXoHHa4Y0z3ag2HqwjmZk";
